// Shared 'About the app' screen (lib/shared/about).

const Map<String, dynamic> aboutUz = {
  'version_label': 'Versiya {version} ({build})',
  'tagline': 'O\'zbekistonning eng yirik mebel bozori. Minglab mebel mahsulotlarini qulay narxlarda topib, bir necha daqiqada buyurtma bering.',
  'terms_of_use': 'Foydalanish shartlari',
  'privacy_policy': 'Maxfiylik siyosati',
  'copyright': '© 2026 Woody',
  'title': 'Ilova haqida',
  'terms_body': 'Ushbu foydalanish shartlari Woody ilovasi (keyingi o\'rinlarda "Ilova") foydalanuvchilari uchun mo\'ljallangan va Ilova orqali taqdim etiladigan xizmatlardan foydalanish qoidalarini belgilaydi.\n\n1. Xizmatlardan foydalanish\n\nIlovadan foydalanish uchun siz kamida 18 yoshda bo\'lishingiz yoki ota-onangiz yoxud qonuniy vakilingizning roziligi bilan harakat qilishingiz lozim. Foydalanuvchi o\'z hisobi orqali amalga oshirilgan barcha harakatlar uchun to\'liq javobgar hisoblanadi. Hisob ma\'lumotlarini uchinchi shaxslarga berish qat\'iyan taqiqlanadi.\n\n2. Buyurtmalar va to\'lovlar\n\nIlova orqali berilgan barcha buyurtmalar uchun belgilangan narxlar va yetkazib berish shartlari amal qiladi. Sotuvchi tomonidan tasdiqlangan buyurtmani bekor qilish yoki o\'zgartirish uchun Woody mijozlar xizmati bilan bog\'lanish talab etiladi. To\'lovlar xavfsiz to\'lov tizimlari orqali amalga oshiriladi; Woody to\'lov kartasi ma\'lumotlarini saqlamaydi.\n\n3. Mas\'uliyat chegaralari\n\nWoody platforma sifatida harakat qilib, sotuvchi va xaridor o\'rtasidagi savdoni osonlashtiradi. Mahsulot sifati, yetkazib berish muddatlari va boshqa savdo shartlari bo\'yicha yuzaga kelgan nizolarda Woody vositachi sifatida ko\'maklashadi, ammo to\'liq javobgarlik sotuvchi zimmasida qoladi. Fors-major holatlari (tabiiy ofatlar, tashqi tarmoq uzilishlari va shu kabilar) da Woody mas\'uliyatdan ozod etiladi.',
  'privacy_body': 'Woody ilovasi foydalanuvchilarning shaxsiy ma\'lumotlarini to\'plash, saqlash va qayta ishlashda O\'zbekiston Respublikasining "Shaxsiy ma\'lumotlar to\'g\'risida"gi qonuniga va xalqaro eng yaxshi amaliyotlarga amal qiladi.\n\n1. Qanday ma\'lumotlar to\'planadi\n\nBiz foydalanuvchi ro\'yxatdan o\'tishda ko\'rsatgan ism, elektron pochta manzili va telefon raqami; buyurtmalar tarixi va yetkazib berish manzillari; qurilma identifikatori va ilova foydalanish statistikasini to\'playmiz. Joylashuv ma\'lumotlari faqat foydalanuvchi roziligidan so\'ng va yetkazib berish manzilini aniqlash maqsadida olinadi.\n\n2. Ma\'lumotlardan foydalanish maqsadlari\n\nTo\'plangan ma\'lumotlar buyurtmalarni qayta ishlash va yetkazib berish, mijozlarga xizmat ko\'rsatish, ilova ishlashini yaxshilash hamda qonuniy majburiyatlarni bajarish uchun ishlatiladi. Shaxsiy ma\'lumotlar uchinchi shaxslarga faqat xizmat ko\'rsatuvchi hamkorlar (to\'lov tizimlari, yetkazib berish xizmatlari) bilan almashiladi va faqat zarur miqdorda uzatiladi.\n\n3. Ma\'lumotlarni himoya qilish va huquqlar\n\nBarcha ma\'lumotlar shifrlangan kanallar orqali uzatiladi va xavfsiz serverllarda saqlanadi. Foydalanuvchi o\'z shaxsiy ma\'lumotlarini ko\'rish, o\'zgartirish yoki o\'chirish huquqiga ega. Bunday so\'rovlar bilan info@woody.uz elektron pochta manziliga murojaat qilishingiz mumkin.',
};

const Map<String, dynamic> aboutRu = {
  'version_label': 'Версия {version} ({build})',
  'tagline': 'Крупнейший мебельный маркетплейс Узбекистана. Находите тысячи мебельных товаров по выгодным ценам и оформляйте заказ за пару минут.',
  'terms_of_use': 'Условия использования',
  'privacy_policy': 'Политика конфиденциальности',
  'copyright': '© 2026 Woody',
  'title': 'О приложении',
  'terms_body': 'Настоящие условия использования предназначены для пользователей приложения Woody (далее — «Приложение») и определяют правила пользования услугами, предоставляемыми через Приложение.\n\n1. Пользование услугами\n\nДля использования Приложения вам должно быть не менее 18 лет либо вы должны действовать с согласия родителей или законного представителя. Пользователь несёт полную ответственность за все действия, совершённые через его учётную запись. Передача данных учётной записи третьим лицам строго запрещена.\n\n2. Заказы и платежи\n\nКо всем заказам, оформленным через Приложение, применяются установленные цены и условия доставки. Для отмены или изменения заказа, подтверждённого продавцом, необходимо связаться со службой поддержки Woody. Платежи осуществляются через защищённые платёжные системы; Woody не хранит данные платёжных карт.\n\n3. Пределы ответственности\n\nWoody, выступая в качестве платформы, упрощает торговлю между продавцом и покупателем. В спорах, связанных с качеством товара, сроками доставки и иными торговыми условиями, Woody содействует как посредник, однако полную ответственность несёт продавец. При обстоятельствах непреодолимой силы (стихийные бедствия, сбои внешних сетей и т. п.) Woody освобождается от ответственности.',
  'privacy_body': 'Приложение Woody при сборе, хранении и обработке персональных данных пользователей соблюдает закон Республики Узбекистан «О персональных данных» и международные передовые практики.\n\n1. Какие данные собираются\n\nМы собираем имя, адрес электронной почты и номер телефона, указанные пользователем при регистрации; историю заказов и адреса доставки; идентификатор устройства и статистику использования приложения. Данные о местоположении используются только с согласия пользователя и в целях определения адреса доставки.\n\n2. Цели использования данных\n\nСобранные данные используются для обработки и доставки заказов, обслуживания клиентов, улучшения работы приложения, а также для выполнения юридических обязательств. Персональные данные передаются третьим лицам только сервис-партнёрам (платёжным системам, службам доставки) и только в необходимом объёме.\n\n3. Защита данных и права\n\nВсе данные передаются по зашифрованным каналам и хранятся на защищённых серверах. Пользователь имеет право просматривать, изменять или удалять свои персональные данные. По таким запросам вы можете обратиться по адресу электронной почты info@woody.uz.',
};

const Map<String, dynamic> aboutEn = {
  'version_label': 'Version {version} ({build})',
  'tagline': 'Uzbekistan\'s largest furniture marketplace. Find thousands of furniture products at great prices and place your order in minutes.',
  'terms_of_use': 'Terms of Use',
  'privacy_policy': 'Privacy Policy',
  'copyright': '© 2026 Woody',
  'title': 'About',
  'terms_body': 'These terms of use are intended for users of the Woody application (hereinafter the "App") and set out the rules for using the services provided through the App.\n\n1. Using the services\n\nTo use the App you must be at least 18 years old, or act with the consent of your parent or legal guardian. The user is fully responsible for all actions performed through their account. Sharing account credentials with third parties is strictly prohibited.\n\n2. Orders and payments\n\nThe set prices and delivery terms apply to all orders placed through the App. To cancel or change an order confirmed by the seller, you must contact Woody customer support. Payments are processed through secure payment systems; Woody does not store payment card details.\n\n3. Limits of liability\n\nActing as a platform, Woody facilitates trade between the seller and the buyer. In disputes over product quality, delivery times and other trade terms, Woody assists as an intermediary, but full liability remains with the seller. In force majeure events (natural disasters, external network outages and the like) Woody is released from liability.',
  'privacy_body': 'When collecting, storing and processing users\' personal data, the Woody app complies with the Republic of Uzbekistan\'s "On Personal Data" law and international best practices.\n\n1. What data is collected\n\nWe collect the name, email address and phone number you provide at registration; order history and delivery addresses; device identifier and app usage statistics. Location data is collected only with the user\'s consent and for the purpose of determining the delivery address.\n\n2. Purposes of data use\n\nThe collected data is used to process and deliver orders, provide customer service, improve app performance, and fulfil legal obligations. Personal data is shared with third parties only with service partners (payment systems, delivery services) and only to the extent necessary.\n\n3. Data protection and rights\n\nAll data is transmitted over encrypted channels and stored on secure servers. The user has the right to view, change or delete their personal data. For such requests you may contact us at info@woody.uz.',
};
